version: '3.8'

services:
  dcharcha-web:
    image: dcharcha.com:latest
    container_name: dcharcha-landing
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5000:5000"

    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

    security_opt:
      - no-new-privileges:true
    read_only: false

    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:5000/ > /dev/null || exit 1"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
